component_depth: 1
languages:
- java
exclude:
- ./ad/.*
- ./ad/test/.*
- ./ad/test/org/.*
- ./ad/test/org/compiere/.*
- ./ad/test/org/compiere/db/.*
- ./base/.*
- ./bin/.*
- ./bin/compiere/.*
- ./bin/compiere/model/.*
- ./bin/org/.*
- ./bin/org/apache/.*
- ./bin/org/apache/ecs/.*
- ./bin/org/apache/ecs/filter/.*
- ./bin/org/apache/ecs/storage/.*
- ./bin/org/apache/ecs/xhtml/.*
- ./bin/org/apache/ecs/xml/.*
- ./bin/org/compiere/.*
- ./bin/org/compiere/acct/.*
- ./bin/org/compiere/api/.*
- ./bin/org/compiere/apps/.*
- ./bin/org/compiere/apps/form/.*
- ./bin/org/compiere/apps/graph/.*
- ./bin/org/compiere/apps/info/.*
- ./bin/org/compiere/apps/search/.*
- ./bin/org/compiere/apps/wf/.*
- ./bin/org/compiere/cm/.*
- ./bin/org/compiere/cm/cache/.*
- ./bin/org/compiere/cm/extend/.*
- ./bin/org/compiere/cm/invoice/.*
- ./bin/org/compiere/cm/request/.*
- ./bin/org/compiere/cm/utils/.*
- ./bin/org/compiere/cm/wiki/.*
- ./bin/org/compiere/cm/xml/.*
- ./bin/org/compiere/common/.*
- ./bin/org/compiere/common/constants/.*
- ./bin/org/compiere/controller/.*
- ./bin/org/compiere/db/.*
- ./bin/org/compiere/esb/.*
- ./bin/org/compiere/excel/.*
- ./bin/org/compiere/framework/.*
- ./bin/org/compiere/grid/.*
- ./bin/org/compiere/grid/ed/.*
- ./bin/org/compiere/grid/tree/.*
- ./bin/org/compiere/images/.*
- ./bin/org/compiere/impexp/.*
- ./bin/org/compiere/install/.*
- ./bin/org/compiere/interfaces/.*
- ./bin/org/compiere/intf/.*
- ./bin/org/compiere/layout/.*
- ./bin/org/compiere/ldap/.*
- ./bin/org/compiere/minigrid/.*
- ./bin/org/compiere/model/.*
- ./bin/org/compiere/plaf/.*
- ./bin/org/compiere/plaf/icons/.*
- ./bin/org/compiere/plaf/sounds/.*
- ./bin/org/compiere/pos/.*
- ./bin/org/compiere/print/.*
- ./bin/org/compiere/print/layout/.*
- ./bin/org/compiere/process/.*
- ./bin/org/compiere/report/.*
- ./bin/org/compiere/report/core/.*
- ./bin/org/compiere/server/.*
- ./bin/org/compiere/session/.*
- ./bin/org/compiere/sla/.*
- ./bin/org/compiere/sqlj/.*
- ./bin/org/compiere/startup/.*
- ./bin/org/compiere/swing/.*
- ./bin/org/compiere/test/.*
- ./bin/org/compiere/tools/.*
- ./bin/org/compiere/translate/.*
- ./bin/org/compiere/udf/.*
- ./bin/org/compiere/util/.*
- ./bin/org/compiere/vos/.*
- ./bin/org/compiere/web/.*
- ./bin/org/compiere/web/sample/.*
- ./bin/org/compiere/wf/.*
- ./bin/org/compiere/wstore/.*
- ./bin/org/compiere/xuom/.*
- ./client/.*
- ./common/.*
- ./data/.*
- ./data/ca_ES/.*
- ./data/da_DK/.*
- ./data/dk_DK/.*
- ./data/en_US/.*
- ./data/fr_FR/.*
- ./data/import/.*
- ./data/in_ID/.*
- ./data/pl_PL/.*
- ./data/ru_RU/.*
- ./data/seed/.*
- ./data/sv_SE/.*
- ./data/th_TH/.*
- ./data/zh_cn/.*
- ./db/.*
- ./db/ERModel/.*
- ./db/database/.*
- ./db/database/Access/.*
- ./db/database/Create/.*
- ./db/database/Functions/.*
- ./db/database/Procedures/.*
- ./db/database/Startup/.*
- ./db/database/Startup/db2/.*
- ./db/database/Startup/oracle/.*
- ./db/database/Startup/pg/.*
- ./db/maintain/.*
- ./db/maintain/Maintenance/.*
- ./db/maintain/Other/.*
- ./db/maintain/Translation/.*
- ./doc/.*
- ./doc/doc/.*
- ./extend/.*
- ./extend/database/.*
- ./extend/database/postgreSQL/.*
- ./install/.*
- ./install/Compiere2/.*
- ./install/Compiere2/images/.*
- ./interfaces/.*
- ./jboss/.*
- ./jboss/bin/.*
- ./jboss/client/.*
- ./jboss/lib/.*
- ./jboss/lib/endorsed/.*
- ./jboss/server/.*
- ./jboss/server/compiere/.*
- ./jboss/server/compiere/conf/.*
- ./jboss/server/compiere/conf/props/.*
- ./jboss/server/compiere/conf/xmdesc/.*
- ./jboss/server/compiere/deploy/.*
- ./jboss/server/compiere/deploy/ejb3.deployer/.*
- ./jboss/server/compiere/deploy/ejb3.deployer/META-INF/.*
- ./jboss/server/compiere/deploy/http-invoker.sar/.*
- ./jboss/server/compiere/deploy/http-invoker.sar/META-INF/.*
- ./jboss/server/compiere/deploy/http-invoker.sar/invoker.war/.*
- ./jboss/server/compiere/deploy/http-invoker.sar/invoker.war/WEB-INF/.*
- ./jboss/server/compiere/deploy/http-invoker.sar/invoker.war/WEB-INF/classes/.*
- ./jboss/server/compiere/deploy/http-invoker.sar/invoker.war/WEB-INF/classes/org/.*
- ./jboss/server/compiere/deploy/http-invoker.sar/invoker.war/WEB-INF/classes/org/jboss/.*
- ./jboss/server/compiere/deploy/http-invoker.sar/invoker.war/WEB-INF/classes/org/jboss/invocation/.*
- ./jboss/server/compiere/deploy/http-invoker.sar/invoker.war/WEB-INF/classes/org/jboss/invocation/http/.*
- ./jboss/server/compiere/deploy/http-invoker.sar/invoker.war/WEB-INF/classes/org/jboss/invocation/http/servlet/.*
- ./jboss/server/compiere/deploy/jboss-bean.deployer/.*
- ./jboss/server/compiere/deploy/jboss-bean.deployer/META-INF/.*
- ./jboss/server/compiere/deploy/jboss-web.deployer/.*
- ./jboss/server/compiere/deploy/jboss-web.deployer/META-INF/.*
- ./jboss/server/compiere/deploy/jboss-web.deployer/ROOT.war/.*
- ./jboss/server/compiere/deploy/jboss-web.deployer/ROOT.war/WEB-INF/.*
- ./jboss/server/compiere/deploy/jboss-web.deployer/ROOT.war/manager/.*
- ./jboss/server/compiere/deploy/jboss-web.deployer/conf/.*
- ./jboss/server/compiere/deploy/jboss-web.deployer/jsf-libs/.*
- ./jboss/server/compiere/deploy/jmx-console.war/.*
- ./jboss/server/compiere/deploy/jmx-console.war/META-INF/.*
- ./jboss/server/compiere/deploy/jmx-console.war/WEB-INF/.*
- ./jboss/server/compiere/deploy/jmx-console.war/WEB-INF/classes/.*
- ./jboss/server/compiere/deploy/jmx-console.war/WEB-INF/classes/org/.*
- ./jboss/server/compiere/deploy/jmx-console.war/WEB-INF/classes/org/jboss/.*
- ./jboss/server/compiere/deploy/jmx-console.war/WEB-INF/classes/org/jboss/jmx/.*
- ./jboss/server/compiere/deploy/jmx-console.war/WEB-INF/classes/org/jboss/jmx/adaptor/.*
- ./jboss/server/compiere/deploy/jmx-console.war/WEB-INF/classes/org/jboss/jmx/adaptor/control/.*
- ./jboss/server/compiere/deploy/jmx-console.war/WEB-INF/classes/org/jboss/jmx/adaptor/html/.*
- ./jboss/server/compiere/deploy/jmx-console.war/WEB-INF/classes/org/jboss/jmx/adaptor/model/.*
- ./jboss/server/compiere/deploy/jmx-console.war/cluster/.*
- ./jboss/server/compiere/deploy/jmx-console.war/images/.*
- ./jboss/server/compiere/deploy/management/.*
- ./jboss/server/compiere/deploy/management/console-mgr.sar/.*
- ./jboss/server/compiere/deploy/management/console-mgr.sar/META-INF/.*
- ./jboss/server/compiere/deploy/management/console-mgr.sar/web-console.war/.*
- ./jboss/server/compiere/deploy/management/console-mgr.sar/web-console.war/META-INF/.*
- ./jboss/server/compiere/deploy/management/console-mgr.sar/web-console.war/WEB-INF/.*
- ./jboss/server/compiere/deploy/management/console-mgr.sar/web-console.war/WEB-INF/classes/.*
- ./jboss/server/compiere/deploy/management/console-mgr.sar/web-console.war/WEB-INF/tlds/.*
- ./jboss/server/compiere/deploy/management/console-mgr.sar/web-console.war/css/.*
- ./jboss/server/compiere/deploy/management/console-mgr.sar/web-console.war/images/.*
- ./jboss/server/compiere/deploy/management/console-mgr.sar/web-console.war/img/.*
- ./jboss/server/compiere/lib/.*
- ./launch/.*
- ./launch/Release/.*
- ./lib/.*
- ./print/.*
- ./serverApps/.*
- ./serverRoot/.*
- ./sqlj/.*
- ./sqlj/db2/.*
- ./sqlj/oracle/.*
- ./sqlj/postgreSQL/.*
- ./tools/.*
- ./tools/lib/.*
- ./tools/lib/crystal/.*
- ./tools/lib/mozilla-1.7.12/.*
- ./tools/lib/mozilla-1.7.12/chrome/.*
- ./tools/lib/mozilla-1.7.12/chrome/icons/.*
- ./tools/lib/mozilla-1.7.12/chrome/icons/default/.*
- ./tools/lib/mozilla-1.7.12/chrome/overlayinfo/.*
- ./tools/lib/mozilla-1.7.12/chrome/overlayinfo/browser/.*
- ./tools/lib/mozilla-1.7.12/chrome/overlayinfo/browser/content/.*
- ./tools/lib/mozilla-1.7.12/chrome/overlayinfo/browser/skin/.*
- ./tools/lib/mozilla-1.7.12/chrome/overlayinfo/communicator/.*
- ./tools/lib/mozilla-1.7.12/chrome/overlayinfo/communicator/content/.*
- ./tools/lib/mozilla-1.7.12/chrome/overlayinfo/cookie/.*
- ./tools/lib/mozilla-1.7.12/chrome/overlayinfo/cookie/content/.*
- ./tools/lib/mozilla-1.7.12/chrome/overlayinfo/editor/.*
- ./tools/lib/mozilla-1.7.12/chrome/overlayinfo/editor/content/.*
- ./tools/lib/mozilla-1.7.12/chrome/overlayinfo/global/.*
- ./tools/lib/mozilla-1.7.12/chrome/overlayinfo/global/skin/.*
- ./tools/lib/mozilla-1.7.12/chrome/overlayinfo/inspector/.*
- ./tools/lib/mozilla-1.7.12/chrome/overlayinfo/inspector/content/.*
- ./tools/lib/mozilla-1.7.12/chrome/overlayinfo/messenger/.*
- ./tools/lib/mozilla-1.7.12/chrome/overlayinfo/messenger/content/.*
- ./tools/lib/mozilla-1.7.12/chrome/overlayinfo/navigator/.*
- ./tools/lib/mozilla-1.7.12/chrome/overlayinfo/navigator/content/.*
- ./tools/lib/mozilla-1.7.12/components/.*
- ./tools/lib/mozilla-1.7.12/components/myspell/.*
- ./tools/lib/mozilla-1.7.12/defaults/.*
- ./tools/lib/mozilla-1.7.12/defaults/autoconfig/.*
- ./tools/lib/mozilla-1.7.12/defaults/isp/.*
- ./tools/lib/mozilla-1.7.12/defaults/isp/US/.*
- ./tools/lib/mozilla-1.7.12/defaults/messenger/.*
- ./tools/lib/mozilla-1.7.12/defaults/messenger/US/.*
- ./tools/lib/mozilla-1.7.12/defaults/pref/.*
- ./tools/lib/mozilla-1.7.12/defaults/profile/.*
- ./tools/lib/mozilla-1.7.12/defaults/profile/US/.*
- ./tools/lib/mozilla-1.7.12/defaults/profile/US/chrome/.*
- ./tools/lib/mozilla-1.7.12/defaults/profile/chrome/.*
- ./tools/lib/mozilla-1.7.12/defaults/wallet/.*
- ./tools/lib/mozilla-1.7.12/greprefs/.*
- ./tools/lib/mozilla-1.7.12/plugins/.*
- ./tools/lib/mozilla-1.7.12/res/.*
- ./tools/lib/mozilla-1.7.12/res/dtd/.*
- ./tools/lib/mozilla-1.7.12/res/entityTables/.*
- ./tools/lib/mozilla-1.7.12/res/fonts/.*
- ./tools/lib/mozilla-1.7.12/res/html/.*
- ./tools/lib/mozilla-1.7.12/res/rdf/.*
- ./tools/lib/mozilla-1.7.12/res/throbber/.*
- ./utils/.*
- ./utils/CommandLine/.*
- ./utils/amazonaws/.*
- ./utils/db2/.*
- ./utils/oracle/.*
- ./utils/postgreSQL/.*
- ./utils/sqlServer/.*
- ./utils/unix/.*
- ./utils/windows/.*
- ./utils_dev/.*
- ./utils_dev/trl/.*
- ./webCM/.*
- ./webStore/.*
- ./xuom/.*
